using System.Net;
using System.Windows;
using System.Windows.Controls;

namespace UI.StationWindows
{
    /// <summary>
    /// Interaction logic for AcceptManagerDialog.xaml
    /// </summary>
    public partial class AcceptManagerDialog
    {
        private readonly Frame _parent;
        private readonly WaitingForManagerPage _waitingForManagerPage; 

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="parent"> the frame this dialog was shown over</param>
        /// <param name="ip">the ip address of the Manager</param>
        /// <param name="waitingForManagerPage">the Page this dialog was shown over</param>
        public AcceptManagerDialog(Frame parent, IPEndPoint ip, WaitingForManagerPage waitingForManagerPage)
        {
            InitializeComponent();
            _parent = parent;
            _waitingForManagerPage = waitingForManagerPage;
            ManagerLabel.Content = ip.Address.ToString();
            Focus();
            PwTextbox.Focus();
            OKButton.IsEnabled = false;
            Title = "Accept Manager";
        }

        /// <summary>
        /// Called when the cancel button is clicked
        /// </summary>
        /// <param name="sender">autogenerated</param>
        /// <param name="e">autogenerated</param>
        private void CancelButtonClick(object sender, RoutedEventArgs e)
        {
            DialogResult = false;
            Close();
        }

        /// <summary>
        /// Called when the OK button is clicked
        /// </summary>
        /// <param name="sender">autogenerated</param>
        /// <param name="e">autogenerated</param>
        private void OkButtonClick(object sender, RoutedEventArgs e)
        {
            _waitingForManagerPage.TypedPassword = PwTextbox.Password;
            DialogResult = true;
            Close();
        }

        /// <summary>
        /// Called when the text in the PwTextbox changes
        /// </summary>
        /// <param name="sender">autogenerated</param>
        /// <param name="e">autogenerated</param>
        private void PwTextboxPasswordChanged(object sender, RoutedEventArgs e)
        {
            OKButton.IsEnabled = PwTextbox.Password.Length > 0;
        }
    }
}
