using System.Windows;

namespace UI.ManagerWindows
{
    /// <summary>
    /// Interaction logic for CheckMasterPasswordDialog.xaml
    /// </summary>
    public partial class CheckMasterPasswordDialog
    {
        private readonly UiHandler _ui;
        public string TypedPassword;
        public bool IsCancel = false;

        /// <summary>
        /// constructor
        /// </summary>
        /// <param name="ui">the UIHandler for this UI</param>
        public CheckMasterPasswordDialog(UiHandler ui)
        {
            InitializeComponent();
            _ui = ui;
            Focus();
            PwTextbox.Focus();
            OKButton.IsEnabled = false;
            Title = "Master Password";
        }

        /// <summary>
        /// Called when the cancel button is clicked
        /// </summary>
        /// <param name="sender">autogenerated</param>
        /// <param name="e">autogenerated</param>
        private void CancelButtonClick(object sender, RoutedEventArgs e)
        {
            DialogResult = true;
            IsCancel = true;
            Close();
        }

        /// <summary>
        /// Called when the OK button is clicked
        /// </summary>
        /// <param name="sender">autogenerated</param>
        /// <param name="e">autogenerated</param>
        private void OkButtonClick(object sender, RoutedEventArgs e)
        {
            DialogResult = _ui.IsMasterPWCorrect(PwTextbox.Password);
            TypedPassword = PwTextbox.Password;
            Close();
        }

        /// <summary>
        /// Called when the text in the PwTextbox changes
        /// </summary>
        /// <param name="sender">autogenerated</param>
        /// <param name="e">autogenerated</param>
        private void PwTextboxPasswordChanged(object sender, RoutedEventArgs e)
        {
            OKButton.IsEnabled = PwTextbox.Password.Length > 0;
        }
    }
}
