using System.Windows;
using System.Windows.Controls;

namespace UI.ManagerWindows {
    /// <summary>
    /// Interaction logic for DataLoadPage.xaml
    /// </summary>
    public partial class DataLoadPage {
        private readonly Frame _parent;
        private readonly UiHandler _ui;

        /// <summary>
        /// constructor
        /// </summary>
        /// <param name="parent">the frame in which this page is displayed</param>
        /// <param name="ui">the UIHandler for this UI</param>
        public DataLoadPage(Frame parent, UiHandler ui) {
            InitializeComponent();
            _parent = parent;
            _ui = ui;
        }

        /// <summary>
        /// Called when the Data browse button is clicked
        /// </summary>
        /// <param name="sender">autogenerated</param>
        /// <param name="e">autogenerated</param>
        private void FileBrowseButtonClick(object sender, RoutedEventArgs e) {
            // Create OpenFileDialog
            var dlg = new Microsoft.Win32.OpenFileDialog { DefaultExt = ".data", Filter = "Data files (.data)|*.data|All Files|*.*", };

            // Display OpenFileDialog by calling ShowDialog method
            var result = dlg.ShowDialog();

            // Get the selected file name and display in a TextBox
            if(result != true)
                return;
            // Open document
            var filename = dlg.FileName;
            filePathTextbox.Text = filename;

            if(!keyPathTextBox.Text.Equals(""))
                nextButton.IsEnabled = true;
        }

        /// <summary>
        /// Called when the back button is clicked
        /// </summary>
        /// <param name="sender">autogenerated</param>
        /// <param name="e">autogenerated</param>
        private void BackButtonClick(object sender, RoutedEventArgs e) {
            _parent.Navigate(new TypeChoicePage(_parent, _ui));
            _ui.DisposeStation();
        }

        /// <summary>
        /// Called when the next button is clicked
        /// </summary>
        /// <param name="sender">autogenerated</param>
        /// <param name="e">autogenerated</param>
        private void NextButtonClick(object sender, RoutedEventArgs e) {
            if(_ui.ImportData(filePathTextbox.Text, keyPathTextBox.Text))
                _parent.Navigate(new OverviewPage(_parent, _ui));
            else {
                MessageBox.Show("Filen du valgte kunne ikke importeres", "Fejl i import", MessageBoxButton.OK);
            }
        }

        /// <summary>
        /// Called when the key browser button is clicked
        /// </summary>
        /// <param name="sender">autogenerated</param>
        /// <param name="e">autogenerated</param>
        private void KeyBrowseButtonClick(object sender, RoutedEventArgs e) {
            // Create OpenFileDialog
            var dlg = new Microsoft.Win32.OpenFileDialog { DefaultExt = ".key", Filter = "Key Files (.key)|*.key|All Files|*.*" };

            // Display OpenFileDialog by calling ShowDialog method
            var result = dlg.ShowDialog();

            // Get the selected file name and display in a TextBox
            if(result != true)
                return;
            // Open document
            var filename = dlg.FileName;
            keyPathTextBox.Text = filename;

            if(!filePathTextbox.Text.Equals(""))
                nextButton.IsEnabled = true;
        }

    }
}
