using System;
using System.Windows;
using System.Windows.Controls;
using Microsoft.Win32;

namespace UI.ManagerWindows
{
    /// <summary>
    /// Interaction logic for EndedElectionPage.xaml
    /// </summary>
    public partial class EndedElectionPage
    {
        private readonly Frame _parent;
        private readonly UiHandler _ui;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="parent">the frame this page is displayed in</param>
        /// <param name="ui">the UIHandler for this UI</param>
        public EndedElectionPage(Frame parent, UiHandler ui)
        {
            _parent = parent;
            _ui = ui;
            var wnd = (StationWindow) Window.GetWindow(_parent);
            if (wnd != null)
            {
                wnd.Width = 600;
                wnd.ExitMenuItem.IsEnabled = false;
                wnd.ExportDataMenuItem.IsEnabled = false;
                wnd.MarkVoterMenuItem.IsEnabled = false;
            }

        InitializeComponent();
        }

        /// <summary>
        /// Called when the browse button is clicked
        /// </summary>
        /// <param name="sender">autogenerated</param>
        /// <param name="e">autogenerated</param>
        private void FileBrowseButtonClick(object sender, RoutedEventArgs e)
        {
            var saveDialog = new SaveFileDialog {Title = "Eksporter Valg Data"};
            saveDialog.Filter = "Data files (*.data)|*.data|All files (*.*)|*.*";
            saveDialog.ShowDialog();

            filePathTextbox.Text = saveDialog.FileName;

            if(!filePathTextbox.Text.Equals(""))
            {
                ExportButton.IsEnabled = true;
            }
        }

        /// <summary>
        /// Called when the export button is clicked
        /// </summary>
        /// <param name="sender">autogenerated</param>
        /// <param name="e">autogenerated</param>
        private void ExportButtonClick(object sender, RoutedEventArgs e)
        {
            if (filePathTextbox.Text.Length > 0)
            {
                _ui.ExportData(filePathTextbox.Text);
                Environment.Exit(0);
            }
            else
            {
                MessageBox.Show("Du har ikke valgt en fil sti", "Ingen fil sti", MessageBoxButton.OK);
            }
        }

    }
}
