/**
  * This file is part of VoteBox.
  * 
  * VoteBox is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License version 3 as published by
  * the Free Software Foundation.
  * 
  * You should have received a copy of the GNU General Public License
  * along with VoteBox, found in the root of any distribution or
  * repository containing all or part of VoteBox.
  * 
  * THIS SOFTWARE IS PROVIDED BY WILLIAM MARSH RICE UNIVERSITY, HOUSTON,
  * TX AND IS PROVIDED 'AS IS' AND WITHOUT ANY EXPRESS, IMPLIED OR
  * STATUTORY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF
  * ACCURACY, COMPLETENESS, AND NONINFRINGEMENT.  THE SOFTWARE USER SHALL
  * INDEMNIFY, DEFEND AND HOLD HARMLESS RICE UNIVERSITY AND ITS FACULTY,
  * STAFF AND STUDENTS FROM ANY AND ALL CLAIMS, ACTIONS, DAMAGES, LOSSES,
  * LIABILITIES, COSTS AND EXPENSES, INCLUDING ATTORNEYS' FEES AND COURT
  * COSTS, DIRECTLY OR INDIRECTLY ARISING OUR OF OR IN CONNECTION WITH
  * ACCESS OR USE OF THE SOFTWARE.
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package votebox.sdl;

class SDLJNI {
  public final static native int VBWRAPPER_get();
  public final static native int vbSDL_Init(int jarg1);
  public final static native void vbSDL_Quit();
  public final static native long vbSDL_SetVideoMode(int jarg1, int jarg2, int jarg3, int jarg4);
  public final static native long vbSDL_LoadBMP(String jarg1);
  public final static native int vbSDL_SetColors(long jarg1, long jarg2, int jarg3, int jarg4);
  public final static native int vbSDL_BlitSurface(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native void vbSDL_UpdateRect(long jarg1, int jarg2, int jarg3, int jarg4, int jarg5);
  public final static native void vbSDL_FreeSurface(long jarg1);
  public final static native int vbSDL_WaitEvent(long jarg1);
  public final static native void vbSDL_SetClipRect(long jarg1, long jarg2);
  public final static native int vbSDL_FillRect(long jarg1, long jarg2, int jarg3);
  public final static native void vbSDL_GetClipRect(long jarg1, long jarg2);
  public final static native long vbSDL_ConvertSurface(long jarg1, long jarg2, int jarg3);
  public final static native int Enabled_Elo_Touchscreen(String jarg1);
  public final static native int Event_Get_Type(long jarg1);
  public final static native int Event_Get_Mouse_X(long jarg1);
  public final static native int Event_Get_Mouse_Y(long jarg1);
  public final static native int Event_Get_Mouse_Button(long jarg1);
  public final static native int Event_Get_Key(long jarg1);
  public final static native void Rect_Set(long jarg1, int jarg2, int jarg3, int jarg4, int jarg5);
  public final static native int Rect_Get_X(long jarg1);
  public final static native int Rect_Get_Y(long jarg1);
  public final static native int Rect_Get_Width(long jarg1);
  public final static native int Rect_Get_Height(long jarg1);
  public final static native int Surface_Set_Pixel(int jarg1, int jarg2, long jarg3, int jarg4, int jarg5, int jarg6, int jarg7);
  public final static native int Surface_Get_Pixel_R(int jarg1, int jarg2, long jarg3);
  public final static native int Surface_Get_Pixel_G(int jarg1, int jarg2, long jarg3);
  public final static native int Surface_Get_Pixel_B(int jarg1, int jarg2, long jarg3);
  public final static native int Surface_Get_Pixel_A(int jarg1, int jarg2, long jarg3);
  public final static native long Surface_Get_Format(long jarg1);
  public final static native long Alloc_Surface(int jarg1, int jarg2);
  public final static native long Alloc_Event();
  public final static native void Free_Event(long jarg1);
  public final static native long Alloc_Rect();
  public final static native void Free_Rect(long jarg1);
}
