#! /bin/sh

for ((i=0; i<1;i=0)); do

  scan-batch-narrow-1 &
	sleep 1
  scan-batch-narrow-2 &
	sleep 1
  scan-batch-narrow-3 &
	sleep 1
  scan-batch-narrow-4 &
	sleep 1
  scan-batch-narrow-5 &
	sleep 1
  scan-batch-narrow-6 &
	sleep 1
  scan-batch-narrow-7 &
	sleep 1
  scan-batch-narrow-8 &

  read text

done

